# Generated by Django 4.1.6 on 2023-04-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(null=True, verbose_name='text1 inf')),
                ('head', models.TextField(null=True, verbose_name='text2 inf')),
                ('tail', models.TextField(null=True, verbose_name='text3 inf')),
                ('type', models.TextField(null=True, verbose_name='text4 inf')),
                ('accepted', models.IntegerField(default=0, verbose_name='Number type')),
            ],
            options={
                'verbose_name_plural': 'Text information',
            },
        ),
        migrations.DeleteModel(
            name='Submit',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
