# Generated by Django 4.1.6 on 2023-04-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_text_delete_submit_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='type',
        ),
    ]
