# Generated by Django 4.1.6 on 2023-04-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_text_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='head_start',
            field=models.IntegerField(null=True, verbose_name='head index'),
        ),
        migrations.AddField(
            model_name='text',
            name='tail_start',
            field=models.IntegerField(null=True, verbose_name='tail index'),
        ),
    ]
