# Generated by Django 4.1.6 on 2023-10-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_text_head_start_text_tail_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeRate',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('X', models.CharField(blank=True, max_length=256, null=True)),
                ('Y', models.CharField(blank=True, max_length=256, null=True)),
                ('FID', models.CharField(blank=True, max_length=256, null=True)),
                ('Year', models.CharField(blank=True, max_length=256, null=True)),
                ('ReportDate', models.CharField(blank=True, max_length=256, null=True)),
                ('ReportTime', models.CharField(blank=True, max_length=256, null=True)),
                ('OccurDate', models.CharField(blank=True, max_length=256, null=True)),
                ('Occur_Time', models.CharField(blank=True, max_length=256, null=True)),
                ('Weekday', models.CharField(blank=True, max_length=256, null=True)),
                ('OffSummary', models.CharField(blank=True, max_length=256, null=True)),
                ('PrimViolat', models.CharField(blank=True, max_length=256, null=True)),
                ('Neighbourh', models.CharField(blank=True, max_length=256, null=True)),
                ('Sector', models.CharField(blank=True, max_length=256, null=True)),
                ('Division', models.CharField(blank=True, max_length=256, null=True)),
                ('CensusTra', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Crime rate',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('housing_no', models.CharField(max_length=256, null=True, verbose_name='room number')),
                ('building_no', models.CharField(blank=True, max_length=256, null=True, verbose_name='building number')),
                ('construction_area', models.CharField(blank=True, max_length=256, null=True, verbose_name='building area')),
                ('using_area', models.CharField(blank=True, max_length=256, null=True, verbose_name='used area')),
                ('type', models.CharField(blank=True, max_length=256, null=True, verbose_name='building type')),
                ('addr', models.CharField(blank=True, max_length=256, null=True, verbose_name='address')),
                ('location', models.CharField(blank=True, max_length=256, null=True, verbose_name='coordinate')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create time')),
                ('user_name', models.CharField(blank=True, max_length=8, null=True, verbose_name='owner')),
            ],
            options={
                'verbose_name_plural': 'Housing information',
            },
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.CharField(default='student', max_length=16, verbose_name='user role'),
        ),
    ]
