# Generated by Django 4.2.4 on 2023-11-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0003_alter_lost_upass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='UPass',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
